### ISSUE TITLE
`BalmUIEvent` not supported  with `ui-menu` on IE11

### ISSUE THREAD

**Issue by ElSamhaa** [balmjs/balm-ui#10]
Using the menu component is working just fine on chrome, however, it throws this error on IE11:

![image](https://user-images.githubusercontent.com/34912861/84769531-46912180-afd6-11ea-86ab-d94435ba1b30.png)

Obviously, IE didn't register the custom event.

**Comment by elf-mouse** [comment]
Thanks @ElSamhaa , This is BalmUI custom event bug. `<ui-menu>` is OK.

I've fixed it in `balm-ui@6.13.0` :)
