### ISSUE TITLE
Selected floating label color is not like it should be

### ISSUE THREAD

**Issue by jowie007** [balmjs/balm-ui#103]
**Development Relevant Information:**

- BalmUI version: 9.39.1
- Browser: Firefox/Edge/Chrome
- Operating System: Windows 11

### Description:
When I select an element wich has an floating label like a TextField or a Select-Element, the floating label is displayed in the default purple color.

### Steps To Reproduce:
In my main.js I wrote the following code:

`createApp(App)
  .use(BalmUI, {
    $theme: {
      'background': '#fff',
      'primary' : "#000",
      'on-primary': '#fff',
      'secondary' : "#000",
      'on-secondary': '#fff',
      'surface': '#fff',
      'on-surface': '#000',
      'error': '#b00020',
      'on-error': '#fff',
    },
  })
  .use(BalmUIPlus)
  .use(router)
  .use(store)
  .mount('#app')`

This works fine for all elements except the elements with a floating label.

For the TextField I used this code:

`    <ui-textfield class="m-2" v-model="username" required>
      Username </ui-textfield
    ><br />`

PS.: Thanks for your amazing work :)

**Comment by elf-mouse** [comment]
Hi @jowie007 , it's a design flaw of MDC web

See [here](https://github.com/balmjs/balm-ui/issues/14#issuecomment-693291554) for solutions

Thanks again :)

**Comment by jowie007** [comment]
Thank you, now it works fine :)
