### ISSUE TITLE
xd.a is not a constructor

### ISSUE THREAD

**Issue by zarbi4734** [balmjs/balm-ui#104]
Hello, I am running the latest version on Balm ui on vue3 and I have the following error in the console (it's also blocking all my component from loading)
![image](https://user-images.githubusercontent.com/25125670/148661699-c837ca3f-7ec1-47e1-88db-e53db56dfe36.png)

**Comment by elf-mouse** [comment]
Sorry @zarbi4734 , I can't reproduce the problem at the moment.

Can you please provide the steps to reproduce or demo?

**Comment by zarbi4734** [comment]
> Sorry @zarbi4734 , I can't reproduce the problem at the moment.
> 
> Can you please provide the steps to reproduce or demo?

I am using Vue3 Typescript and I just installed Balme. Nothing more.

**Comment by elf-mouse** [comment]
Hi @zarbi4734 ,

I have updated the typescript test demos, maybe they can help you, see [here](https://github.com/balmjs/balm-ui/tree/9.x/test-vue).

You need to add some definitions yourself, and I will update the definition file for typescript support in a later version.

Or, you can use `balm-ui` source code usage for debug, see [docs](https://next-material.balmjs.com/#/guide/advanced) for detail.

**Comment by Explie** [comment]
Hi there,

I am having the same issue with usage of Balm-UI in a vue-cli project.
![2022-01-12 10_58_21-my-app](https://user-images.githubusercontent.com/15127270/149118279-34c42360-cf98-4169-8839-fca23170617e.png)

**Steps to reproduce.**

1. Install NodeJS in the latest LTS (node 16.13.2, npm 8.1.2)
2. Install vue-cli `npm install -g @vue/cli` (@vue/cli 4.5.15)
3. Create a new project with **Vue 3** Default template `vue create my-app` and cd into
`>Default (Vue 3) ([Vue 3] babel, eslint)`
`cd my-app`
4. Install latest balm-ui `npm install --save balm-ui`
5. Add Alias to webpack in `vue.config.js`:
```
configureWebpack: {
    resolve: {
        alias: {
            'balm-ui-plus': 'balm-ui/dist/balm-ui-plus.js',
            'balm-ui-css': 'balm-ui/dist/balm-ui.css'
        }
    }
}
```
6. Add to Vue in `main.js`: 
```
import BalmUI from "balm-ui/src/scripts";

createApp(App).use(BalmUI).mount('#app')
```
7. Start webpack dev server `npm run serve`


I'll try to check with source code usage, but I believe I won't be a big help here.

Best

**Comment by Explie** [comment]
Argh, excuse the confusion I was using the BalmUI 8.x tree for Vue 3 which obviously isn't supported ... 
I switched to `npm install --save balm-ui@next` and the error is gone. Maybe thats the case for you @zarbi4734 as well?

**Comment by elf-mouse** [comment]
@Explie , thank you very much! Case solved :)

Hi @zarbi4734 , please try again:

- For Vue2

  ```sh
  yarn add vue balm-ui
  ```

- For Vue3

  ```sh
  yarn add vue@next balm-ui@next
  ```

**Comment by zarbi4734** [comment]
> @Explie , thank you very much! Case solved :)
> 
> Hi @zarbi4734 , please try again:
> 
> * For Vue2
>   ```shell
>   yarn add vue balm-ui
>   ```
> * For Vue3
>   ```shell
>   yarn add vue@next balm-ui@next
>   ```

Yep after npm install --save balm-ui@next it's working,  the mistake I made was to install the vue-2 version.
Thank you !
