### ISSUE TITLE
Vue, BalmUI and SCSS - can't find "@material/feature-targeting/feature-targeting"

### ISSUE THREAD

**Issue by Explie** [balmjs/balm-ui#106]
**Development Relevant Information:**

- BalmUI version: "^9.40.0"
- Vue version: "^3.0.0"
- Sass version: "^1.48.0"
- sass-loader version: "^8.0.2"

### Description:
I've setup a simple vue cli project with BalmUI support and it works fine. Afterwards I tried overwriting some material style in SCSS as described in the docs but I am always running in an Sass Import Error for `@material/feature-targeting/feature-targeting`
```
Syntax Error: SassError: Can't find stylesheet to import.
   ╷
29 │ @use '@material/feature-targeting/feature-targeting';
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@material\theme\_theme.scss 29:1  @forward
  node_modules\@material\theme\_index.scss 17:1  @use
  src\styles\_vendor.scss 3:1                    @use
  E:\Desktop\AssetInv\frontend\src\styles\main.scss 3:1                                      root stylesheet
```

My `vendor.scss` looks like the following:
```
@use '@material/theme' as theme-variables with (
  $primary: var.$primaryColor,
  $secondary: #018786,
);

//!* import BalmUI styles *!
@use 'balm-ui/dist/balm-ui';

.mdc-data-table__header-cell{
  font-weight: 700
}

.mdc-fab {
  box-shadow: none !important;
}
```

What am I missing here? I do understand it has a problem with importing `@use '@material/feature-targeting/feature-targeting';` in the `node_modules\@material\theme\_theme.scss`  but why is it failing. All other imports seem to work fine. Also the problem was non existent when bootstrapping with BalmJS but i couldn't figure out what BalmJS does different here.

Thanks!

**Comment by elf-mouse** [comment]
Hi @Explie , 

I assume you are using `pnpm`?
Please use `yarn` or `npm` first!

**Comment by elf-mouse** [comment]
Hi @Explie ,

This problem is due to the lack of some common compatible configurations in your manually built scaffold, such as the options of sass-loader. so you need add sassOptions

- `vue.config.js`

  ```js
  module.exports = {
    // ...
    css: {
      loaderOptions: {
        sass: {
          sassOptions: {
            includePaths: ["node_modules"],
          },
        },
      },
    },
  };
  ```

And, if you choose sass entry, don't use css entry

- `src/main.js`
  
  ```js
  // import 'balm-ui-css' // css entry
  import './styles/vendor.scss' // sass entry
  ```

Also, if you don't copy _balm-ui/fonts_ to the project _src_ folder, you need to additionally rewrite the sass variable for icon

- `src/styles/vendor.scss`

  ```scss
  @use 'balm-ui/components/icon' with (
    $font-path: '../../node_modules/balm-ui/fonts'
  );
  ```

**Comment by Explie** [comment]
Hi @elf-mouse,

Works like a charm. Many thanks to you.

I already though I am missing an include of the node_modules folder but neither the Vue- nor the SASS Loader documentation were particularly helpful. In the end it was a webpack option...

Have a nice day and many thanks!
