### ISSUE TITLE
$theme.colors is not a function

### ISSUE THREAD

**Issue by Ivan1105** [balmjs/balm-ui#107]
**Development Relevant Information:**

- BalmUI version: 9.40.3
- Browser: Chrome 97
- Operating System: Windows 11

### Description:

I wanted to change the theme colors and used `this.$theme.colors(color)` as it was declared

```
interface BalmUITheme {
  colors(color: ThemeColor): void;
}
```

But the browser reports `Uncaught TypeError: this.$theme.colors is not a function`

It works well if I write as `(this.$theme.colors as ThemeColor) = color`.

**Comment by elf-mouse** [comment]
Hi @Ivan1105 , It's a getter, not a function.

This is a mistake in the theme documentation. I have updated.

Thank you very much :)

> NOW, `balm-ui@9` is the new default version.
