### ISSUE TITLE
Dialog and select conflict

### ISSUE THREAD

**Issue by siloam** [balmjs/balm-ui#108]
**Development Relevant Information:**

- BalmUI version: 9.39.1
- Browser: Chrome
- Operating System: Windows 10

### Description:

Select's options are not visible when select is placed in a dialog window. They're cut by dialog main area. 

### Steps To Reproduce:
n/a

**Comment by elf-mouse** [comment]
Hi @siloam ,

This bug has been fixed! You can try balm-ui(v10.x) and enjoy it :)

Thanks again~

**Comment by siloam** [comment]
Thank you too!
