### ISSUE TITLE
Text Field questions in password type.

### ISSUE THREAD

**Issue by ltxhhz** [balmjs/balm-ui#111]
**Development Relevant Information:**

- BalmUI version: 9.41.0✨
- Browser: Microsoft Edge 版本 97.0.1072.76 (官方内部版本) (64 位)
- Operating System: Windows 10 pro

### Description:
1. The button that shows the plaintext seems to only appear when the text field is empty, I don't know if that's what you planned, but I would like to be able to show the button when the text field is empty, or add an option for this, if not, that's fine. [GIF demo](https://s4.ax1x.com/2022/02/05/Hm3X8A.gif)
2. I want that effect
![image](https://user-images.githubusercontent.com/51697596/152575037-7f56bdbb-872c-40ef-962a-7c16ec9cc8ef.png)
But if I write it this way, it doesn't seem to work.
![image](https://user-images.githubusercontent.com/51697596/152574765-4de65dd4-1791-4e3f-b8da-808a483b60d4.png)
![image](https://user-images.githubusercontent.com/51697596/152574234-995e762b-6473-47c5-8324-bdfe224f6bc8.png)
![image](https://user-images.githubusercontent.com/51697596/152574049-a5a798e2-e416-4ef4-957c-4656f41bff54.png)
I don't know what went wrong.

### Steps To Reproduce:
n/a

**Comment by ltxhhz** [comment]
Great library, by the way. 👍
Happy New Year.

**Comment by ltxhhz** [comment]
In the second question, I seem to have found the problem. It seems that the only way to avoid error is to keep the two tags adjacent.
![image](https://user-images.githubusercontent.com/51697596/152627386-ce4f2230-996b-4b81-bf8e-1ebdea80760a.png)
![image](https://user-images.githubusercontent.com/51697596/152627316-cd20ffea-6cdd-4aa9-8c00-d85d952a9da5.png)
![image](https://user-images.githubusercontent.com/51697596/152627405-727c6fcd-65e5-44fe-b5fa-340888ab0b46.png)
![image](https://user-images.githubusercontent.com/51697596/152627410-29963e9c-c8c4-4296-8b3c-dffa2345f2c9.png)

**Comment by elf-mouse** [comment]
Hi @ltxhhz , 

Yes, you are right. No other tags can be inserted between `<ui-textfield>` and `<ui-textfield-helper>`, which is how the MDC web is currently designed

Thank you very much for your issue. I will optimize the `<ui-textfield-helper>` hints

Happy Lunar New Year. 🐂年大吉~

**Comment by elf-mouse** [comment]
UI新版本以及文档都已经更新完毕！再次感谢支持BalmUI :)

**Comment by ltxhhz** [comment]
@elf-mouse 您好，感谢回复和更新，但这个议题还有第一个问题没有解答：密码文本域只有第一次聚焦输入才会显示右侧“显示密码”的按钮。
请问这个确实是这样设计的吗？
如果是这样就可以关闭这个议题了。
再次感谢✨

**Comment by ltxhhz** [comment]
明白了，感谢大佬解惑🎉

> 问题1属于IE浏览器的默认行为，你可以使用 `<input type="password">` 测试一波就明白了
