### ISSUE TITLE
Support for vue 3

### ISSUE THREAD

**Issue by leibale** [balmjs/balm-ui#12]
Hi,

What's the plan regarding support for Vue 3?

Thanks

**Comment by elf-mouse** [comment]
@leibale , Thank you for your attention.

 The current stable version of [BalmUI](https://material.balmjs.com/) is 7.x,  and we are about to release version 8.0 following the official progress of Google MDC Web. At the same time, we are indeed preparing to gradually support Vue 3 from 8.0.

**Comment by leibale** [comment]
Perfect :)

If there's any way I can help, please let me know

**Comment by elf-mouse** [comment]
@leibale Sure! Thank you so~~ much :)

**Comment by elf-mouse** [comment]
Hi @leibale,

[BalmUI](https://material.balmjs.com/) new versions released now:

- `balm-ui` (8.0) for Vue 2.0
- `balm-ui@next` (9.0 beta) for Vue 3.0

> Let's try new, and I will update the document for Vue 3.0 in the near future :)

**Comment by leibale** [comment]
@elf-mouse wow, that was fast :)

I'm checking it right now, will let you know in case I found any bugs
