### ISSUE TITLE
Issue updating data table content

### ISSUE THREAD

**Issue by winer222** [balmjs/balm-ui#120]
Hello!
Firstly, love using balm ui, I am running into an issue, specifically relating to updating data tables after the fact, my app pulls data from a websocket and displays it in the table, when doing this I get errors logged in the console relating to nextTick. When a message is received it is decoded, and the contents of the data array in the table is updated.

`[Vue warn]: Error in nextTick: "TypeError: Cannot read properties of undefined (reading 'hideProgress')"`

If I am doing something wrong please do tell me.
Thanks In Advance,
Adam Mathieson

**Comment by elf-mouse** [comment]
Hi @winer222 , can you provide the reproduction steps?

**Comment by winer222** [comment]
Hello, I am sure you are extremely busy, what I have found is the data table cannot take arrays of objects with a single key that then points to the object, changing the data structure seems to resolve the issue.

Thanks for your time,

Kind regards,
Adam Mathieson

**Comment by elf-mouse** [comment]
Sorry @winer222, I did not reproduce the problem. I'm using `balm-ui@10.3.1`

```html
<ui-table :data="data" :thead="thead" :tbody="tbody">
  <template #record="{ data: { record } }">
    {{ record.id }}: {{ record.name }}
  </template>
</ui-table>
```

```js
export default {
  data() {
    return {
      data: [
        {
          record: {
            id: 1,
            name: 'user1'
          }
        },
        {
          record: {
            id: 2,
            name: 'user2'
          }
        }
      ],
      thead: ['Title'],
      tbody: [
        {
          slot: 'record'
        }
      ]
    };
  },
  mounted() {
    setTimeout(() => {
      this.data = [
        {
          record: {
            id: 3,
            name: 'user3'
          }
        },
        {
          record: {
            id: 4,
            name: 'user4'
          }
        }
      ];
    }, 3000);
  }
};
```

**Comment by winer222** [comment]
Not a problem, I understand you are busy, I was running this in balm `8.46.3` which is clearly an old version, so I will probably update it. Either way, at least in my case the issue is resolved by updating the data structure so that each element in the array has the data directly rather than in a sub-object.

Kind regards,
Adam Mathieson

**Comment by elf-mouse** [comment]
I will check the v8 version for this bug as soon as possible

Thanks again :)

**Comment by elf-mouse** [comment]
Hi @winer222 , I have confirmed the problem

It's a very old bug, you can reinstall `balm-ui@8` (Latest version: v8.49.4) and enjoy it (No breaking changes)

Thanks again~ Have a great weekend!

**Comment by winer222** [comment]
Thanks very much for all your work on this, I will update my version.
