### ISSUE TITLE
How do I get an instance of Quill in the Editor component?

### ISSUE THREAD

**Issue by ltxhhz** [balmjs/balm-ui#126]
你好
我昨天将我的库从` 9.x` 升级到 `10.3.1`，发现之前通过 `ref` 获取 ui-editor 实例，再从中取 `$editor` 属性的方法已经行不通了
由于我的项目中需要手动插入内容的地方比较多，需要调用 `insertText`、`insertEmbed` 等方法，并且还自定义了 Blots ，所以需要获取 Delta 来序列化
所以想问一下还有其他方法吗

**Comment by elf-mouse** [comment]
感谢提问，我会尽快修复这个问题，追加抛出quill实例

**Comment by ltxhhz** [comment]
感谢
thx
🎉
