### ISSUE TITLE
ui-select not showing it's validation message

### ISSUE THREAD

**Issue by HDShabe** [balmjs/balm-ui#128]
**Development Relevant Information:**

- BalmUI version: 9.42.1
- Browser: Chrome
- Operating System: Windows

Hi,

I've got a couple of controls, one of which is a ui-select, the other a ui-textfield, coupled with a BalmUI Validator.

```
<div class="row">
  <ui-select v-model="viewModel.testDropdown"
             :options="viewModel.testOptions"
             helper-text-id="testDropdown-helper-text"
             defaultValue=""
             defaultLabel="Select one"
             fullwidth
             :type=1>
      Test dropdown
  </ui-select>
  <ui-textfield-helper id="testDropdown-helper-text"
                       :valid-msg="validMsg.testDropdown">
  </ui-textfield-helper>
  </div>
  
  <div class="row">
  <ui-textfield v-model="viewModel.testTextField"
                helper-text-id="testTextField-helper-text"
                fullwidth
                :type=1>
      Text text field
  </ui-textfield>
  <ui-textfield-helper id="testTextField-helper-text"
                       :valid-msg="validMsg.testTextField">
  </ui-textfield-helper>
</div>

```

```
const validations = {
      testDropdown: {
          label: 'Test dropdown',
          validator: 'required'
      },
      testTextField: {
          label: 'Test text field',
          validator: 'required'
      }
  }
```

```
 export default defineComponent({
        data() {
            return {
                balmUI: useValidator(),
                validations,
                validMsg: {}
            }
        },
```

```
 submit() {
    let result = this.balmUI.validate(this.viewModel);
    let { valid, validMsg } = result;
    this.validMsg = validMsg;
    
    if (valid) {
   //submit form
}

```

However, when submitting the form what I get is this;

![image](https://user-images.githubusercontent.com/42472545/162945562-a7166ad7-7f22-4b07-82ef-1a1438624ad2.png)

as you can see, for the text field the message appears as normal, though for the select it doesn't. The select seems to think it's invalid as the control has the red outline, just no accompanying error text.

I tried updating BalmUI to latest (v10.4.0) but I had some other error which I'll raise a separate ticket for.

Let me know if you need any more information,
Thanks.

**Comment by elf-mouse** [comment]
Hi @HDShabe , The corresponding component of `<ui-select>` is `<ui-select-helper>`

**Comment by HDShabe** [comment]
Ah I missed that in the documentation! Are ui-textfield-helper and ui-select-helper the only ones, or are there more? For radio button groups etc?

Thanks!

**Comment by elf-mouse** [comment]
> Ah I missed that in the documentation! Are ui-textfield-helper and ui-select-helper the only ones, or are there more? For radio button groups etc?
> 
> Thanks!

MDC officially did not design more helper components. You can customize the form field helper component.

**Comment by HDShabe** [comment]
Cool, thanks for the information, really appreciate it.
