### ISSUE TITLE
[Feature Request] Support `unplugin-vue-components`

### ISSUE THREAD

**Issue by llk2yq** [balmjs/balm-ui#133]
### Description:
RT

[`unplugin-vue-components`](https://github.com/antfu/unplugin-vue-components)

**Comment by llk2yq** [comment]
@elf-mouse

**Comment by llk2yq** [comment]
有自动导入的使用例子吗？

**Comment by elf-mouse** [comment]
@llk2yq , 参考一下[这里](https://github.com/elf-mouse/unplugin-vue-components/blob/main/src/core/resolvers/balm-ui.ts)

**Comment by llk2yq** [comment]
@elf-mouse 这个PR不是没有被合并吗
