### ISSUE TITLE
`ui-select` dropdown aligned incorrectly in ui-dialog content

### ISSUE THREAD

**Issue by hiddehs** [balmjs/balm-ui#135]
**Development Relevant Information:**

- BalmUI version: since [v10.2.0](https://github.com/balmjs/balm-ui/releases/tag/v10.2.0) / currently tested on 10.8.1 
- Browser: Chrome
- Operating System: macOS

### Description:

ui-select is always center aligned on page when in dialog because flex + `align-items: center` in the .mdc-select--in-dialog substyle. Also smaller (2 items) ui-selects are not aligned the way they align when used outside the dialog.
Introduced by bugfix for #46 / https://github.com/balmjs/balm-ui/commit/1696e69baf01a648da8744dc8392d5db249ab055

How is the ui-select supposed to look like in the dialog?

### Steps To Reproduce:
Create long `ui-select` in `ui-dialog.ui-dialog-content`

```vue 
<ui-dialog
      v-model="active"
      fullscreen
    >
<ui-dialog-content>
    <ui-select
      v-model="x"
      outlined
      class="inline w-auto"
      :options="[ ...[...Array(60).keys()].map((i)=>({label: 'Second ' + (i ), value: `${i}`}))]"
      label="Second"
    />
....
```
![Schermafbeelding 2022-06-08 om 23 04 09](https://user-images.githubusercontent.com/20111194/172720855-575b0e19-185b-4889-ac07-0270089db674.png)

**Comment by elf-mouse** [comment]
@hiddehs , thank you very very much

It's css bug, it has been fixed now.

**Comment by hiddehs** [comment]
@elf-mouse thank you very much for fixing the issue directly. amazing maintenance. I'll do a small modification PR to prevent small lists from not taking the whole screen-h space ;) 

is the select-menu always supposed to be centered in the dialog? I thought that the select list had the same behavior inside the dialog as in a normal page (I understand that positioning fixed elements on anchors in fixed ones is hard..) ? (https://vuetifyjs.com/en/components/dialogs/#form)

**Comment by jochemvogel** [comment]
thanks
