### ISSUE TITLE
Remote autocomplete should not filter results

### ISSUE THREAD

**Issue by frankkoornstra** [balmjs/balm-ui#143]
**Development Relevant Information:**

- BalmUI version: 10.9.3
- Browser: irrelevant
- Operating System: irrelevant

### Description:
When using `remote` with the Autocomplete input, the options coming back from the server are filtered (just like non-remote) which often doesn't make sense since the server already applied a filter in the backend. Can we get an option to disable this filtering behavior or provide a custom filter function as a property?

Let me give you an example: I want to autocomplete Google Places. I built a backend that gives access to the Google Places API and the autocomplete sends the query "main street London". I get several options back from the backend but since the autocomplete applies a filter, I don't see them:
* Mainstreet Pictures London
* Electronics Main in London
* Main street, London (because of the comma)

When using the `remote` option, chances are pretty high the data set is too big to filter in the frontend so the backend that is closes to the data does it. Applying the "second" filter in the frontend does not make sense in that case. If we can set a custom filter function, we can just let all results go through.

**Comment by elf-mouse** [comment]
Hi @frankkoornstra , v10.11.0 add new prop `filterKeywords` and this bug has been fixed.

Thank you very much~

**Comment by frankkoornstra** [comment]
Great, thank you!
