### ISSUE TITLE
ripple / underline not working in latest 10.x for ui-textfield

### ISSUE THREAD

**Issue by davija** [balmjs/balm-ui#147]
**Development Relevant Information:**

- BalmUI version: 10.12.10
- Browser: Chrome 89 & MS Edge 87 (Chrome 105 on Ubuntu 22.04)
- Operating System: Windows 10

### Description:
Using the latest VueJS 3 created using `npm init vue@latest` (included balm-test.zip file) and then setting up following the documentation on the balm-ui website, the textfields do not have the expected ripple / underline.

### Steps To Reproduce:
Included minimal repro project...
extract project
run `yarn install` in the project folder
run `yarn dev` to start the app
browse to http://localhost://5173

Expected ripple to be shown like in the documentation for a filled input, actual result attached.

Simple minimal example:
[balm-test.zip](https://github.com/balmjs/balm-ui/files/9688062/balm-test.zip)

Expected to look something like this:
![expected-ripple](https://user-images.githubusercontent.com/138913/193367420-4a219b28-85e8-4c10-afef-2acd9abefef0.png)

Ends up looking like this (notice the missing underline):
![actual-missing-ripple](https://user-images.githubusercontent.com/138913/193367428-a8472cb4-53c9-469f-a55e-0ef17e3bdbe9.png)

A couple of things to note, the "expected" image shows the input in it's non-focused form, however when you click on it, the label moves up and the underline changes to purple.

The "actual" image shows the input in it's focused state.  The ripple / underline does not appear in either the focused or non-focused state

**Comment by elf-mouse** [comment]
- `./assets/base.css`

  ```css
  *,
  *::before,
  *::after {
    box-sizing: border-box;
    margin: 0;
    /* position: relative; // The problem */
    font-weight: normal;
  }
  ```
