### ISSUE TITLE
Select options not showing outside of data grid row template again

### ISSUE THREAD

**Issue by HDShabe** [balmjs/balm-ui#158]
Hi @elf-mouse ,

I've just tried updating my version of balm-ui from 10.9.3 to 10.13.4 and noticed that where I have select inputs inside of data grid row templates, the select options now don't show outside of the current row, cutting off basically the entirety of the content of the select options. I believe this was an issue in the past that we resolved, would you mind having a look if this is something that's broken again?

edit: Similar to the original issue from here: https://github.com/balmjs/balm-ui/issues/91

Cheers.

**Comment by elf-mouse** [comment]
Hi @HDShabe , because the `<ui-select>` has the new `inside` prop in version 10.10.0

Now, there are now two solutions:

Method 1 - overwrite `<ui-table>` styles

```html
<ui-table :data="requestData" :thead="thead" :tbody="tbody">
  <template #selectInput="{ data }">
    <ui-select v-model="mySelectedValue" :options="myOptions">
      Label
    </ui-select>
  </template>
</ui-table>
```

```css
.mdc-data-table__table-container,
.mdc-data-table__cell {
  overflow: initial;
}

.mdc-deprecated-list {
  padding: 0;
}
```

Method 2 - enable the `inside` prop of `<ui-select>`

```html
<ui-table :data="requestData" :thead="thead" :tbody="tbody">
  <template #selectInput="{ data }">
    <ui-select v-model="mySelectedValue" :options="myOptions" inside>
      Label
    </ui-select>
  </template>
</ui-table>
```

**Comment by HDShabe** [comment]
Hi @elf-mouse 

Apologies for getting back to you so late on this one, I've tried the above and the "inside" prop implementation works : ) 

Cheers!
