### ISSUE TITLE
Add support for button type submit

### ISSUE THREAD

**Issue by leibale** [balmjs/balm-ui#16]
Currently `ui-button` component sets the button type to `button` without any option to change it to submit.
An API like `inputType` in `ui-text-field` component would be awesome.

Thanks

**Comment by elf-mouse** [comment]
**Not recommended.**

Please use `@click="handleClick"` event to control your logic.

**Comment by leibale** [comment]
But with the `@click` handler the user won't be able to submit the form by pressing the enter key in while focusing an input in the form, and it's also not very good for accessibility?

Can you please explain why `button[type="submit"]` is not recommended?

**Comment by elf-mouse** [comment]
New prop `nativeType` has been added to `<ui-button>` in latest versions for Vue2&3.

Because `<form>` **submit** is not friendly to SPA, the same event, `@click="onSubmit"` is better:

```html
<form @submit.prevent="onSubmit">
  ...
  <ui-form-field>
    <ui-button native-type="submit">Submit</ui-button>
  </ui-form-field>
</form>
```

VS

```html
<ui-form>
  ...
  <ui-form-field>
    <ui-button @click="onSubmit">Submit</ui-button>
  </ui-form-field>
</ui-form>
```

```js
export default {
  // ...
  methods: {
    onSubmit() {
      let result = this.validator.validate(this.formData);
      let { valid, validMsg } = result;

      if (valid) {
        // ...
      }
    }
  }
};
```

**Comment by leibale** [comment]
Thanks :)
