### ISSUE TITLE
 Validator with the "individual usage" configuration has no validation rules

### ISSUE THREAD

**Issue by loicdekester** [balmjs/balm-ui#163]
**Development Relevant Information:**

- BalmUI version: 10.18.1
- Browser: Chrome Version 111.0.5563.147 (Official Build) (64-bit)
- Operating System: Widows 10

### Description:

I am trying to use the validator with the "individual usage" configuration but I get console warnings saying the field doesn't have a validation rule. ==> The field 'length' is missing a validation rule: 'required'
Even though required is a default rule.
I even tried a custom rule and didn't have more luck.

### Steps To Reproduce:

Here is a link to see the error: https://stackblitz.com/edit/vue-exxmy9?file=src/main.js
The form has a input event that triggers the validation.

**Comment by elf-mouse** [comment]
Hi @loicdekester , you need to modify your code like this:

- `HelloWorld.vue`

```js
import { useValidator } from 'balm-ui/plugins/validator'; // Because of individual usage

// ...

function validate() {
  const { valid, validMsg } = validator.validate(formData);
  // ...
}
```

**Comment by loicdekester** [comment]
Hi @elf-mouse,

Thanks for getting back to me so fast.

I see the problem, both in main.js and in components when we use the validator we have to get it from 'balm-ui/plugins/validator' for individual usage.
