### ISSUE TITLE
The dependency "vue" is incorrectly capitalized in v9

### ISSUE THREAD

**Issue by XiaoPangxie732** [balmjs/balm-ui#19]
```
ERROR  Failed to compile with 2 errors

This dependency was not found:

* Vue in ./node_modules/balm-ui/dist/balm-ui-plus.js, ./node_modules/balm-ui/dist/balm-ui.js

To install it, you can run: npm install --save Vue
```

**Comment by elf-mouse** [comment]
不太清楚你这个问题是啥意思，请具体说明（比如你的开发环境或使用的脚手架），可以贴一下你的代码示例！

**Comment by XiaoPangxie732** [comment]
这是编译的时候报的错，脚手架是vue-cli

**Comment by XiaoPangxie732** [comment]
标题我可能没说清楚，我已经安装了vue，这个日志里提示没有安装依赖“Vue”（大小写有问题，v应该是小写）

**Comment by elf-mouse** [comment]
抱歉，先前文档只更新了BalmCLI的使用部分，没来得及更新Vue官方脚手架的使用，现在我已更新完毕，具体请参照 [快速入门](https://next-material.balmjs.com/#/guide/quickstart) 中的 __Vue CLI 或 Vite__ 部分

```js
import { createApp } from 'vue';
import App from './App.vue';
import './index.css';
import BalmUI from 'balm-ui';
import BalmUIPlus from 'balm-ui/dist/balm-ui-plus';
import 'balm-ui/dist/balm-ui.css';

const app = createApp(App);

// using `.default`: because the non-esm-bundler for default vue
app.use(BalmUI.default);
app.use(BalmUIPlus.default);

app.mount('#app');
```

**Comment by XiaoPangxie732** [comment]
还是照样报错，前面贴出来的是控制台的报错，现在贴一下网页的
```
Failed to compile.

./node_modules/balm-ui/dist/balm-ui-plus.js
Module not found: Error: [CaseSensitivePathsPlugin] `D:\WebSite\maxpixel-studios-website\node_modules\Vue\dist\vue.runtime.esm-bundler.js` does not match the corresponding path on disk `vue`.
```
![image](https://user-images.githubusercontent.com/47449269/95447607-8f5d5380-0994-11eb-9f42-4bd732000fa6.png)
![image](https://user-images.githubusercontent.com/47449269/95447771-d64b4900-0994-11eb-96a0-592f5cd763cc.png)

**Comment by elf-mouse** [comment]
如果你使用的是Vue 2.x，请安装`balm-ui` (v8)

因为 `balm-ui@next` (v9) 只支持 Vue 3.x

**Comment by XiaoPangxie732** [comment]
就是用的vue 3

**Comment by XiaoPangxie732** [comment]
我在dist文件夹的js文件里找到了` require("Vue") `，改成` require("vue") `就能正常编译了
![image](https://user-images.githubusercontent.com/47449269/95454332-e5cf8f80-099e-11eb-9fc1-e6ee32cf2766.png)


![image](https://user-images.githubusercontent.com/47449269/95454496-1fa09600-099f-11eb-9235-1492805443dc.png)

**Comment by elf-mouse** [comment]
感谢 @XiaoPangxie732 

因为目前我只跑了 BalmCLI 和 Vite，明天我会抽空专门把 VueCLI 的初始化跑一遍，谢谢~

**Comment by elf-mouse** [comment]
这是我打包UI库延用 Vue2 时的一个bug，`9.0.0-beta.14` 已修复此问题！

@XiaoPangxie732 万分感谢 :)

**Comment by XiaoPangxie732** [comment]
谢谢，问题已经解决了

**Comment by XiaoPangxie732** [comment]
不过我还有个问题，这个dialog应该怎么用，我用了没效果，开发者工具里的控制台输出是这样的

![image](https://user-images.githubusercontent.com/47449269/95621395-2ebd3c00-0aa4-11eb-8b09-eb7b3228bd6d.png)

**Comment by elf-mouse** [comment]
- 默认用法

  ```js
  import BalmUI from 'balm-ui';
  import 'balm-ui/dist/balm-ui.css';
  
  app.use(BalmUI);
  ```

- 独立用法

  ```js
  import UiButton from 'balm-ui/components/button';
  import UiDialogComponents from 'balm-ui/components/dialog';
  import 'balm-ui/components/core.css';
  import 'balm-ui/components/button/button.css';
  import 'balm-ui/components/dialog/dialog.css';
  
  app.use(UiButton);
  app.use(UiDialogComponents);
  ```

---

`<ui-dialog>` 用法

```html
<template>
  <ui-button @click="open = true">Test</ui-button>

  <ui-dialog v-model="open">
    <ui-dialog-title>Title</ui-dialog-title>
    <ui-dialog-content>Content</ui-dialog-content>
    <ui-dialog-actions></ui-dialog-actions>
  </ui-dialog>
</template>
```

```js
export default {
  data() {
    return {
      open: false
    };
  }
};
```

> 详情可参考 [BalmUI Dialog 文档](https://next-material.balmjs.com/#/feedback/dialog)，其中可能还有一些 Vue2 的残留文档，今天应该会全部更新成 Vue3 文档

**Comment by elf-mouse** [comment]
Hi, @XiaoPangxie732 

现在 [UI 文档](https://next-material.balmjs.com/) 基本已全部更新，后续我会逐步更新中文文档
> 当前UI最新版本 `v9.0.0-beta.16`

**Comment by XiaoPangxie732** [comment]
谢谢
