### ISSUE TITLE
Receiving,- & releasing focussed style on datepicker (with extended config)

### ISSUE THREAD

**Issue by MarcoTroost** [balmjs/balm-ui#22]
Hi Elf-Mouse,

If one extends the (flatpickr) configuration for the datepicker, issues with the focussed style on the textfield seem to occur.

If I choose `altinput: true` (human readable date), the texfield never gets the focussed styling,

<img width="353" alt="Schermafbeelding 2020-10-20 om 08 10 57" src="https://user-images.githubusercontent.com/16369103/96547919-3606f580-12ad-11eb-8031-e67aaa799a0d.png">

If I choose `minDate: new Date().fp_incr(15)` (15 days from today), the texfield never releases the focussed styling

<img width="364" alt="Schermafbeelding 2020-10-20 om 08 11 23" src="https://user-images.githubusercontent.com/16369103/96547928-3b644000-12ad-11eb-85aa-aa7f7979acc2.png">

full config:

```
config: {
                    altInput: true,
                    altFormat: "j F Y",
                    dateFormat: 'd-m-Y',
                    defaultDate: 'today',
                    minDate: new Date().fp_incr(15),
                    maxDate: new Date().fp_incr(100),
                    locale: lang.nl,
                    disable: [
                        function(date) {
                            return (date.getDay() === 0 || date.getDay() === 6);

                        }
                    ],
                },
```

kind regards,

Marco

**Comment by elf-mouse** [comment]
Hi Marco, 

Thanks your issue.

It's a focused bug. I will fix it as soon as possible for the related extension components.

**Comment by elf-mouse** [comment]
Hi Marco, 

This bug is fixed.

- `balm-ui@8.5.1` for Vue2
- `balm-ui@9.0.0-rc.4` for Vue3

You can update and try again :)

**Comment by MarcoTroost** [comment]
Hi Elf-Mouse,

Thank you for the update. Bug is fixed!
