### ISSUE TITLE
balm init vue#next my-project generates error

### ISSUE THREAD

**Issue by Tusshu** [balmjs/balm-ui#23]
Followed instructions given here:  [https://next-material.balmjs.com/#/guide/quickstart]

Executing balm init vue#next my-project generates following error:

(node:11801) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'latest' of undefined
    at /Users/kale/.config/yarn/global/node_modules/balm-cli/lib/check-version.js:21:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
macOS: 10.15.7;  balm cli: 2.4.0;  balm-core: 3.7.0

**Comment by elf-mouse** [comment]
Hi @Tusshu ,

Thank you very much for your issue.

I will check and fix this bug (for `yarn`) as soon as possible, today!
You can use `npm install -g balm-core balm-cli` instead and try again.

**Comment by elf-mouse** [comment]
Hi Tusshu, please tell me your `node` and `yarn` version, thanks

**Comment by Tusshu** [comment]
I removed earlier install and tried the command you suggested and it worked.
Thanks!

**Comment by elf-mouse** [comment]
Perfect!

I have verified, there is no problem with Balm CLI.

But I found a new bug for `vue@3.0.1+` with template [`vue`](https://github.com/balmjs/template-vue/tree/next) and [`vue-expert`](https://github.com/balmjs/template-vue-expert/tree/next).

`__VUE_HMR_RUNTIME__ is not defined` in development, `vue@3.0.0` is ok!!!

so I have updated two templates' config:

```js
// for alias
{
  '@vue/runtime-core': '@vue/runtime-core/dist/runtime-core.esm-bundler.js'
}
```

If you have any problems, please let me know! Thanks again :)
