### ISSUE TITLE
ui-autocomplete source personnalisation

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#32]
Hey,

I'm working on a private project. i'm using a lot of ui-autocomplete for searching elements.

With the actual source prop for `ui-autocomplete` i have to format all my call for matching `{'label': '', value: ''}`

It's possible to have a source format parameter ?

```js
app.use(BalmUIPlus, {
  UiAutocomplete: {
    sourceFormat: {
      label: 'name',
      value: 'id'
    }
  }
});
```

Thank you

**Comment by elf-mouse** [comment]
hi jfrag,

`source` prop itself supports `string[]` or `object[]`.

Please see `<ui-autocomplete>` [api docs](https://material.balmjs.com/#/data-input/autocomplete) for details.

**Comment by jfrag** [comment]
Hi @elf-mouse ,

I need to overwrite `label` and `value` properties of the `object[]` with specific properties like `name` and `id`

The doc say:

> An array of objects with label and value properties: [ { label: 'Choice1', value: 'value1' }, ... ]

Sorry if I am not clear enough.
I'm not very good in English...

**Comment by elf-mouse** [comment]
Sorry, because there is no detailed description of this content in the document. I will update the document later.

You can add any fields to object, like this:

```js
{
  label: 'Choice Text', // required
  value: '',
  id: '',
  name: ''
}
```

**Comment by jfrag** [comment]
Ok,

I made a modification in the 9.x autocomplete.vue branch. can you review it ?

[autocomplete.zip](https://github.com/balmjs/balm-ui/files/5608243/autocomplete.zip)

**Comment by elf-mouse** [comment]
@jfrag , perfect!

It's a good idea. I will consider adding this modification.

**Comment by jfrag** [comment]
Hi @elf-mouse 

Have you planned to build a new version for vue3 with this feature is the coming days ?

**Comment by elf-mouse** [comment]
Yes, I will release a new version next week.

Recently, I have been busy solving `balm-core` windows bugs and optimization work, so I have delayed some plans for UI.

**Comment by elf-mouse** [comment]
`balm-ui@9.3.0` released :)

**Comment by jfrag** [comment]
Hi @elf-mouse 

Thank you very much !
