### ISSUE TITLE
bundle size weirdness

### ISSUE THREAD

**Issue by gvas** [balmjs/balm-ui#34]
First of all, thanks for this excellent library!

balm-ui 8.10.0

I found that importing the default BalmUI module results in smaller js bundle size than importing the individual components/directives/plugins.  The css bundle, by contrast, is larger in the default case, as expected.

Bundle | Size
--- | ---
chunk-vendors...js (default) | 611.63 KiB
chunk-vendors...js (individual) | 911.78 KiB
app...css (default) | 417.97 KiB
app...css (individual) | 210.83 KiB

The imported individual components/directives/plugins were:
```
import $theme from 'balm-ui/plugins/theme'
import $typography from 'balm-ui/plugins/typography'
import UiIcon from 'balm-ui/components/icon'
import UiButton from 'balm-ui/components/button'
import UiIconButton from 'balm-ui/components/icon-button'
import UiTopAppBar from 'balm-ui/components/top-app-bar'
import UiGridComponents from 'balm-ui/components/grid'
import UiForm from 'balm-ui/components/form'
import UiFormField from 'balm-ui/components/form-field'
import UiDivider from 'balm-ui/components/divider'
import UiDrawerComponents from 'balm-ui/components/drawer'
import UiMenuComponents from 'balm-ui/components/menu'
import UiTextfieldComponents from 'balm-ui/components/textfield'
import UiCheckbox from 'balm-ui/components/checkbox'
import UiListComponents from 'balm-ui/components/list'
import UiCardComponents from 'balm-ui/components/card'
import vRipple from 'balm-ui/directives/ripple'
```

Am I missing something?

**Comment by elf-mouse** [comment]
Thanks @gvas , I will check that.

**Comment by gvas** [comment]
It seems that the extra bytes come from the core-js polyfills which are included in each of the individual components/directives/plugins.

**Comment by elf-mouse** [comment]
@gvas ,

Thank you so~much for locating the key point of the problem :)

__Bundle__ | __Size__
--- | ---
default BalmUI | 445 KiB
individual BalmUI (your example) | 472 KiB (A small amount of duplicate code)

I have republished `8.15.0` and you can try it again.

**Comment by gvas** [comment]
Thanks! The new version has indeed shaved off a significant portion of the individual components, although the default/full build is still smaller. As I understand there will always be some redundant code in the components because they are truly independent from each other by design. They can't share their common boilerplate and polyfills.
I realized that I need to import the components' sources instead of their built versions. This way my own build system can more efficently optimize the build.

So instead of:

```
import Vue from 'vue'
import UiButton from 'balm-ui/components/button'

Vue.use(UiButton)
```

I can import the sources directly:
```
import Vue from 'vue'
import UiButton from 'balm-ui/src/scripts/components/button'

Vue.use(UiButton)
```

This way the bundle size finally became smaller then the default/full build:

Bundle | Size
--- | ---
individual components, BalmUi v8.13.1 | 1418.18 KiB
individual components, BalmUi v8.15.0 | 980.38 KiB
default/full build | 748.96 KiB
importing the sources | 519.31 KiB


Maybe it's worth to include this in the docs. This is a common scenario, I imagine.

**Comment by elf-mouse** [comment]
Hi @gvas , 

You're right. Source code usage is the code optimization solution. It is better than the built versions.

__Bundle__ | __Size__
--- | ---
`balm-ui`(default usage) | 445 KiB
`balm-ui`(source code usage) | 422 KiB
`UiButton` (individual usage) | 28 KiB
`UiButton` (source code usage) | 18.4 KiB

In fact, the documentation of the source code usage has always existed. See [2.3 Source Code Usage](https://material.balmjs.com/#/guide/advanced).

Thank you again for your support to BalmUI :)

**Comment by gvas** [comment]
Indeed. I skipped that section of the documentation because the first sentence ("Just for developing and debugging components") suggested that that technique is meant only for the BalmUI developers.
Anyway, I think this issue is solved, I am closing it now. Thanks!

**Comment by gvas** [comment]
One more thing: by default `babel-loader` ignores all files inside `node_modules`. If you import the BalmUi sources then you have to specify them explicitly for transpilation. Supposing the application was created with vue-cli you have to modify `vue.config.js`:

```
module.exports = {
  ...
  transpileDependencies: [
    'balm-ui',
    'flatpickr',
    'quill'
  ]
}
```

**Comment by elf-mouse** [comment]
Thanks gvas, I will update docs.
