### ISSUE TITLE
ui-form-field with v-if missing class

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#42]
Hi

If i put a ```v-if``` on a ```ui-form-field``` the component didn't have the class ```mdc-form__item``` and the lignment is broken.

bug implemented with the last version of balm-ui for vue3

**Comment by elf-mouse** [comment]
Yes, the class `mdc-form__item` will only be automatically added when the `<ui-form>` is first initialized.

Use dynamic form like this:

```html
<ui-form>
  <template #default="{ itemClass }">
    <ui-form-field :class="itemClass">
      <label>Label1</label>
      <ui-textfield></ui-textfield>
    </ui-form-field>
    <ui-form-field v-if="show" :class="itemClass">
      <label>Label2</label>
      <ui-textfield></ui-textfield>
    </ui-form-field>
  </template>
</ui-form>
```

**Comment by jfrag** [comment]
Hi,

it work !

Thakn's for your help
