### ISSUE TITLE
Tooltip in list wrong placement

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#49]
Hi,

Tooltip on a ```ui-icon-button``` inside a ```ui-list``` never appear

**Comment by elf-mouse** [comment]
Hi @jfrag ,

Because `<ui-item>` default style is `overflow: hidden`

In this case, you can overwrite css or use `<ui-tooltip>` component usage
```

**Comment by elf-mouse** [comment]
Hi @jfrag ,

`<ui-tooltip-anchor>` (from mdc@11 preview) will be added in the next version (next week) to help solve this problem :)

**Comment by elf-mouse** [comment]
Hi @jfrag ,

now, you can upgrade to `9.18.1`, then use new tooltip like this:

```html
<ui-list>
  <ui-item>
    <div v-tooltip="'Tips text'" aria-describedby="tooltip-id"></div>
  </ui-item>
</ui-list>
```

**Comment by jfrag** [comment]
hi @elf-mouse 

Thank you !
