### ISSUE TITLE
Make Documentation Website Cleaner

### ISSUE THREAD

**Issue by theArtechnology** [balmjs/balm-ui#5]
I was wondering between other UI Framework or this one. Other UI Framework has cleaner documentation UI, but I love this one because, this, has more compatibility with browsers, and doesn't break.

It would be nice, if the documentation page was cleaner. We can take example on [stasson - vue-mdc-adapter documentation page](https://stasson.github.io/vue-mdc-adapter/#/component/card).

A glimpse on the website structure: 
https://github.com/stasson/vue-mdc-adapter/blob/master/demo/component.vue

I would be glad to help :)

**Comment by elf-mouse** [comment]
Hi @theArtechnology , thank you for your attention and suggestions, we are about to upgrade and improve the documentation for balm-ui@5.x :)
