### ISSUE TITLE
$toast appear in the middle of the page

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#52]
The last update induce a position bug of $toast module

![bug $toast](https://user-images.githubusercontent.com/352579/113839476-003cc700-9790-11eb-881d-12e7d6254442.png)

**Comment by elf-mouse** [comment]
Hi @jfrag , 

It's fixed now.

And the new option `position` of the toast has been added in `9.21.0`. See [toast docs](https://next-material.balmjs.com/#/feedback/toast) for detail.

**Comment by jfrag** [comment]
THX
