### ISSUE TITLE
Ability to set a data attribute on data input component

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#53]
Hi,

it is possible to add the possibility to set a data attr to any data input ```ui-textfield```, ```ui-select``` and others ?

something like ```<ui-textfield input-data-old-val="foo"><ui-textfield>```

Thanks for your hard work !

**Comment by elf-mouse** [comment]
You could use `attrs` prop, like this:

```html
<ui-textfield :attrs="{ 'data-old-val': foo }"></ui-textfield>
```

> `<ui-checkbox>`, `<ui-radio>`, `<ui-switch>` also have `attrs` prop, but `<ui-select>` do not have it

**Comment by jfrag** [comment]
Ah ok !

Thank you
