### ISSUE TITLE
<ui-select> should not get validated instantly when mounted

### ISSUE THREAD

**Issue by schellmax** [balmjs/balm-ui#56]
**Development Relevant Information:**

- BalmUI version: https://cdn.jsdelivr.net/npm/balm-ui
- Browser: Chrome
- Operating System: OSX

### Description:
When using a Select field, it gets immediately validated (when mounted) and renders an error state (red label, red line at the bottom) in case it's invalid (eg required field with empty value in first option).
This is in contrast to Textfields, which only get validated once the user leaves the field (on blur).
The only way of rendering Select fields the same as Textfields initially is by setting 'options' to an empty array.

### Steps To Reproduce:
see https://codepen.io/schellmax01/pen/GRWvwBP

<img width="701" alt="balm_ui_select" src="https://user-images.githubusercontent.com/1886396/120064758-37cc3f00-c06e-11eb-8c6e-70e00826acc9.png">

**Comment by elf-mouse** [comment]
@schellmax ,

Thanks a lot. I would check and fix this problem when I have time later.

And welcome to PR.

**Comment by elf-mouse** [comment]
Hi @schellmax , I verified the `<ui-select>` again, please don't use empty value in select's options, if you need to set the default empty value option, you can use `defaultLabel` and `defaultValue` props

Have a great weekend! Thanks again :)
