### ISSUE TITLE
ui-chips dynamic options

### ISSUE THREAD

**Issue by jfrag** [balmjs/balm-ui#62]
Hi,

I'm trying to make a ```<ui-chips type="filter"></ui-chips>``` with dynamic options attr
But when the Array of options is updated, i cannot reset the v-model and new chip cannot be selected

**Comment by jfrag** [comment]
Here is an example:
https://codepen.io/jfrag/pen/RwVPJvw

**Comment by elf-mouse** [comment]
Hi @jfrag ,

Thanks for your PR.

Now, `v9.31.3` is OK.
