### ISSUE TITLE
Using with vite

### ISSUE THREAD

**Issue by peterbud** [balmjs/balm-ui#65]
Thanks @elf-mouse  for this project!

I was wondering whether there is a good minimal example how to use with vite.js? I have read the [docs](https://next-material.balmjs.com/#/guide/quickstart), but I could not make the material design icons working. I have seen in the documentation at least two config files (balmrc.js, balm.config.js), and I'm not sure which one to use, and also I could not figure out where to put the css or scss file to make it work with vite.

**Comment by elf-mouse** [comment]
Hi @peterbud ,

Thank you for your interest in BalmUI.

See new [demo](https://github.com/balmjs/balm-ui/tree/9.x/test-vue/vite)

**Comment by peterbud** [comment]
Hi @elf-mouse , many thanks for the new demo.  have tried to run it, ang got the following error message:
```txt
[plugin:vite:css] Can't find stylesheet to import.
  ╷
2 │ ┌ @use '@material/theme/variables' as theme-variables with (
3 │ │   $primary: #f00
4 │ │ );
  │ └─^
  ╵
  src\App.vue 2:1  root stylesheet
```
I'm not sure how to fix it.

**Comment by peterbud** [comment]
As I see the `material-components-web` dependency was missing
