### ISSUE TITLE
An error about the document

### ISSUE THREAD

**Issue by yanziqing25** [balmjs/balm-ui#66]
The DEMO on the [page](https://next-material.balmjs.com/#/navigation/tabs) show the "ui-tab" usage:
`<ui-tab type="icon"></ui-tab>`
`<ui-tab type="both"></ui-tab>`
But set those prop string value doesn't work.
The current type value are "text", "iconOnly" or "textWithIcon".
![2](https://user-images.githubusercontent.com/11330778/127346585-2b6a7587-7f2c-4d9d-86d7-183da54f406a.png)
`<ui-tab type="text"></ui-tab>`
`<ui-tab type="iconOnly"></ui-tab>`
`<ui-tab type="textWithIcon"></ui-tab>`
Those wrong values are deprecated ,Did you forget to update the doc?

**Comment by elf-mouse** [comment]
Thanks @yanziqing25 :)

Now, it's OK!
