### ISSUE TITLE
`layout-grid-cell` prop:`align` practically useless without exposing a `grid-layout-inner` component

### ISSUE THREAD

**Issue by ElSamhaa** [balmjs/balm-ui#7]
I believe the title says it all.

component :
```vue
<template>
  <ui-grid :style="{ border: 'solid blue', height: '100%' }">
    <ui-grid-cell class="yellow"></ui-grid-cell>
    <ui-grid-cell class="yellow" align="bottom">hello</ui-grid-cell>
    <ui-grid-cell class="yellow"></ui-grid-cell>
  </ui-grid>
</template>

<script>
export default {}
</script>

<style lang="scss">
@use 'balm-ui/dist/balm-ui.scss';
.yellow {
  background: yellow;
}
</style>
```
![image](https://user-images.githubusercontent.com/34912861/81697848-9d4e8d00-9465-11ea-8058-8b01c451fb1c.png)

component with limited workaround:
```css
div.mdc-layout-grid__inner {
  height: 100%;
  background: cyan;
}
```
![image](https://user-images.githubusercontent.com/34912861/81696825-b9056380-9464-11ea-9c2d-496bb8f35281.png)

**Comment by elf-mouse** [comment]
Thanks @ElSamhaa .

Items are defined to stretch, by default, taking up the height of their corresponding row. 

See my simple demo.

```html
<template>
  <ui-grid class="demo">
    <ui-grid-cell class="yellow" columns="3" align="top">
      <div v-for="i in 1" :key="i">item {{ i }}</div>
    </ui-grid-cell>
    <ui-grid-cell class="yellow" columns="3" align="middle">
      <div v-for="i in 2" :key="i">item {{ i }}</div>
    </ui-grid-cell>
    <ui-grid-cell class="yellow" columns="3" align="bottom">
      <div v-for="i in 3" :key="i">item {{ i }}</div>
    </ui-grid-cell>
    <ui-grid-cell class="yellow" columns="3">
      <div v-for="i in 4" :key="i">item {{ i }}</div>
    </ui-grid-cell>
  </ui-grid>
</template>

<script>
export default {};
</script>

<style>
.yellow {
  background: yellow;
}

.demo {
  border: 1px solid;
}

.demo .mdc-layout-grid__inner {
  background: cyan;
}
</style>
```

![test](https://user-images.githubusercontent.com/2597430/81777209-f2040d80-9522-11ea-97cd-22cd29cf8c36.png)

The `align` prop is OK :)

**Comment by ElSamhaa** [comment]
I know the `align` prop is ok, appears so in my second screenshot. However, this isn't my whole point. But I see your point though, in order for me to be able to middle-align a cell, I need to fill it with contents (div behavior). 
My explained use case is when I need to middle-align relative to the parent when there's no inner content to stretch the container.
There might be other use cases supporting my suggestion in the future. you can close this issue for the time being if you don't see my point considered for the time being.

**Comment by elf-mouse** [comment]
It has been optimized in `balm-ui@6.6.2`. Thanks again! :)

**Comment by siloam** [comment]
What is the proper way to create many rows?

**Comment by elf-mouse** [comment]
See [Material Design guidelines: Layout grid](https://material.io/design/layout/responsive-layout-grid.html) for details
