### ISSUE TITLE
Allow to disable ripple effect for specific elements

### ISSUE THREAD

**Issue by Aragur** [balmjs/balm-ui#71]
Currently I'm using the Drawer with the `ui-nav-item` component.  
As I want to toggle the active state on navigation I don't want the ripple effect to interfere.  
Is there a way to disable the ripple on component basis or via a directive?

**Comment by elf-mouse** [comment]
Sorry, it is not supported at the moment.

Maybe I will consider adding this prop in subsequent versions.

Thanks @Aragur

**Comment by elf-mouse** [comment]
Hi @Aragur , the latest version has fixed this issue, thank you :)
