### ISSUE TITLE
Autocomplete component throwing error on pressing enter key

### ISSUE THREAD

**Issue by chindhy** [balmjs/balm-ui#78]
**Development Relevant Information:**

- BalmUI version: ^9.38.0
- Browser: Version 94.0.4606.81 (Official Build) (64-bit)
- Operating System: WIndows 10 pro

### Description: 
Autocomplete component throws an error when user press enter key. This does not happen if I enter a keyword and there are no matching items in source.
My code:
<template>
  <ui-autocomplete
    v-model="keyword"
    :source="products"
    :minlength="3"
    fullwidth
  ></ui-autocomplete>
</template>

### Steps To Reproduce:
Press enter key without keyword.
Press enter key after typing a keyword but do not select matching item.

**Comment by elf-mouse** [comment]
Sorry @chindhy , I can't reproduce the problem.

Can you provide the complete code or error message?

**Comment by StoneMoney** [comment]
I've also run into this, it even happens on the documentation site itself!

for @elf-mouse
* Start entering text for autocomplete, be sure to enter text that will show options
* Do not highlight or select any options
* Press enter

![ProblemRecreation](https://user-images.githubusercontent.com/17057173/144866725-f924c5bc-f368-44f2-8f2c-fcb92167b44d.gif)

**Comment by elf-mouse** [comment]
@StoneMoney , Thanks for you PR :)
