### ISSUE TITLE
How to make button with secondary background color?

### ISSUE THREAD

**Issue by format1981** [balmjs/balm-ui#79]
How to make button with secondary background color?

I expect something like
`<ui-button secondary>Label</ui-button>`

**Comment by elf-mouse** [comment]
Hi @format1981 ,

You can overwrite theme color by sass. Like this:

```scss
@use '@material/theme/theme-color' with (
  $primary: #6200ee,
  $secondary: #018786,
);
```

See [theme color](https://next-material.balmjs.com/#/theme/color) sass docs

**Comment by format1981** [comment]
https://next-material.balmjs.com/#/theme/color

At the top of the page you can see 2 buttons: primary and secondary.
But you can`t see code of this buttons.

**Comment by elf-mouse** [comment]
> https://next-material.balmjs.com/#/theme/color
> 
> At the top of the page you can see 2 buttons: primary and secondary. But you can`t see code of this buttons.

You can use `$theme.getThemeClass(style)` api.
