### ISSUE TITLE
Drawer with nested lists

### ISSUE THREAD

**Issue by Kestami** [balmjs/balm-ui#80]
Hi, hopefully this is the right place to ask a question, I couldn't find another means of asking!

Is it possible to create a drawer that has nested lists in it?

- item a
- item b
- >>> item b.1
- >>> item b.2
- item c

Thanks in advance!

**Comment by elf-mouse** [comment]
Hi @Kestami ,

```html
<ui-list-group>
  <ui-list-group-subheader>List Title 1</ui-list-group-subheader>
  <ui-nav>
    <ui-nav-item v-for="i in 3" :key="i">Item 1-{{ i }}</ui-nav-item>
  </ui-nav>

  <ui-list-divider></ui-list-divider>

  <ui-list-group-subheader>List Title 2</ui-list-group-subheader>
  <ui-nav>
    <ui-nav-item v-for="i in 3" :key="i">Item 2-{{ i }}</ui-nav-item>
  </ui-nav>
</ui-list-group>
```

See [List docs](https://next-material.balmjs.com/#/data-display/list) for detail
