### ISSUE TITLE
Could not find a declaration file for module 'balm-ui'. '/node_modules/balm-ui/dist/balm-ui.js'

### ISSUE THREAD

**Issue by rawalprashant** [balmjs/balm-ui#81]
**Development Relevant Information:**

- BalmUI version: 9.38.0
- Browser: Google Chrome
- Operating System: Windows

### Description:

I am working with Laravel API and Vue JS 3 development and I am using balmUI when I tried to call it using the app.js file it says the "Could not find a declaration file for module"

import { createApp } from 'vue'

require('./bootstrap')
import App from './App.vue'
import axios from 'axios'
import router from './router'

import BalmUI from 'balm-ui'; // Official Google Material Components

const app = createApp(App)
app.use(BalmUI); // Mandatory

app.config.globalProperties.$axios = axios;
app.use(router)
app.mount('#app')

**Comment by elf-mouse** [comment]
Hi @rawalprashant , `balm-ui@9.40+` has started to support TS.

For the problem in laravel, you can also refer to [this](https://github.com/balmjs/balm-ui/issues/86#issuecomment-1018099873).

Thanks again :)

**Comment by rawalprashant** [comment]
@elf-mouse Thanks for the latest update, Yes I will go through your reference to fix my issue with laravel.
