### ISSUE TITLE
Non-Interactive Lists

### ISSUE THREAD

**Issue by winer222** [balmjs/balm-ui#85]
For the web-app I am currently working on we use quite a number of lists, many of which should not be interactive, I can see that there is a flag for it that can be set on the list but it seems not do do anything, the class that it is trying to apply doesn't seem to exist.

Thanks for your help in advance,
Adam Mathieson

**Comment by elf-mouse** [comment]
Hi @winer222 ,

The non-Interactive list has been updated. Please use the latest version for BalmUI.

Thank you so~ much :)

**Comment by winer222** [comment]
Thanks very Much!
