### ISSUE TITLE
ui-pagination - customize "of"

### ISSUE THREAD

**Issue by siloam** [balmjs/balm-ui#87]
Could you provide a prop to customize "of" word? This word differs between languages. Thank you in advance.

**Comment by elf-mouse** [comment]
Not available at the moment, it is recommended to use slot to achieve custom data display.

I will consider adding a prop in the next version

**Comment by elf-mouse** [comment]
Hi @siloam ,

This problem has been optimized in the new version.

Thanks again.

**Comment by elf-mouse** [comment]
Hi @siloam ,

The `ofText` prop has been added in the new version.

Thanks again~
