### ISSUE TITLE
can't manage to work with nuxt3

### ISSUE THREAD

**Issue by terion-name** [balmjs/balm-ui#88]
**Development Relevant Information:**

- BalmUI version: 8.46.3
- Browser: n/a
- Operating System: mac od

### Description:
trying to add balm to nuxt3, on page load getting error:

500
[vite dev] Error loading external ".../node_modules/balm-ui/dist/balm-ui.js".
at file://./.nuxt/dist/server/server.mjs:8158:302
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:8524:3)

### Steps To Reproduce:

package json:
```json
{
  "private": true,
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.1.8",
    "@vitejs/plugin-vue": "^1.9.4",
    "autoprefixer": "^10.4.0",
    "nuxt3": "^3.0.0-27288761.d3fb512",
    "postcss": "^8.3.11",
    "sass": "^1.43.4",
    "sass-loader": "^12.3.0"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.1.5",
    "balm-ui": "^8.46.3",
    "pinia": "^2.0.4"
  }
}
```
added plugin:
```js
import { defineNuxtPlugin } from '#app'
import BalmUI from 'balm-ui'; // Official Google Material Components
import BalmUIPlus from 'balm-ui/dist/balm-ui-plus'; // BalmJS Team Material Components
import 'balm-ui/dist/balm-ui.css';

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(BalmUI);
    nuxtApp.vueApp.use(BalmUIPlus);
})
```
nuxt config:
```js
import { defineNuxtConfig } from 'nuxt3'
import { resolve } from "path";

export default defineNuxtConfig({
    buildModules: [
        // pinia plugin - https://pinia.esm.dev
        ['@pinia/nuxt'],
        '@intlify/nuxt3'
    ],
    css: [
        'assets/css/main.sass'
    ],
    intlify: {
        vueI18n: {
            locale: 'en'
        },
        localeDir: 'langs'
    },
    vite: {
        resolve: {
            alias: {
                vue: "vue/dist/vue.esm-bundler.js",
                "balm-ui-plus": "balm-ui/dist/balm-ui-plus.esm.js",
                "balm-ui-css": "balm-ui/dist/balm-ui.css"
            }
        }
    }
})


```

**Comment by terion-name** [comment]
If I import like this:
```js
import { defineNuxtPlugin } from '#app'
import BalmUI from 'balm-ui/dist/balm-ui-next'; // Official Google Material Components
// import BalmUIPlus from 'balm-ui/dist/balm-ui-plus'; // BalmJS Team Material Components
import 'balm-ui/dist/balm-ui.css';

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(BalmUI);
    // nuxtApp.vueApp.use(BalmUIPlus);
})
```
then error is:
500 __vite_ssr_import_1__.ssrRenderSuspense is not a function

**Comment by terion-name** [comment]
run yarn add balm-ui@next

installed "balm-ui": "^9.38.1"

getting:

500
Cannot call a class as a function
at xm (file://./.nuxt/dist/server/server.mjs:8163:604139)
at new t (file://./.nuxt/dist/server/server.mjs:8163:611264)
at n. (file://./.nuxt/dist/server/server.mjs:8163:610636)
at new n (file://./.nuxt/dist/server/server.mjs:8163:612766)
at $id_df7e8dd2 (file://./.nuxt/dist/server/server.mjs:8163:612399)
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:8646:3)

**Comment by elf-mouse** [comment]
Hi @terion-name ,

The SSR of BalmUI 9.x is not fully tested, I will gradually update and improve this feature.
Now, please set `ssr: false` first if you use it in `nuxt3`
See [my example](https://github.com/balmjs/balm-ui/tree/9.x/test-vue/nuxt3) by `nuxi`

Thank you so much :)

**Comment by elf-mouse** [comment]
BalmUI 8.x only supports vue2 and nuxt2

**Comment by terion-name** [comment]
@elf-mouse understood. yes, without ssr works. not great, but ok for a while. thank you
