### ISSUE TITLE
Textfield 的 hint 未跟随主题色改变，文档中的textfield也有同样的问题

### ISSUE THREAD

**Issue by Sanlorng** [balmjs/balm-ui#9]
**BalmUI 版本**： 6.6.1
**问题**：在App.vue中初始化主题色为#2196F3，对应的颜色后，text-field的 hint 的 actived状态颜色未跟着主题色改变，依然是默认色浅紫色

> 相关代码

```
    this.$setTheme("primary","#2196F3")  
    this.$setTheme("sencondary","#2196F3")
```
![Snipaste_2020-05-18_17-42-05](https://user-images.githubusercontent.com/26089739/82198943-99bc7980-992f-11ea-9cbf-ddd98df6f4e0.png)
起初以为是自己的问题，查看[官方文档](https://material.balmjs.com/#/theme/color)，并将主题切换成shrine后（其他样例主题也有同样的问题），text-field的 hint 的 actived 状态颜色也是浅紫色，并未跟随主题色变化
![Snipaste_2020-05-18_17-42-45](https://user-images.githubusercontent.com/26089739/82199362-2cf5af00-9930-11ea-83ca-cb9454ae2c7e.png)

**Comment by elf-mouse** [comment]
感谢 @Sanlorng 提的问题，`$setTheme`确实有点问题，我会尽快做调整。

当前推荐使用Sass变量复写即可达成你要的全局主题效果：

```scss
// `/path/to/_vendors.scss`
@use '@material/theme/variables' as theme-variables with (
  $primary: #2196F3,
  $secondary: #2196F3,
);

@use 'balm-ui/dist/balm-ui.scss';
```

**Comment by Sanlorng** [comment]
> 感谢 @Sanlorng 提的问题！
> 
> `$setTheme`确实有点问题，因为`<ui-textfield>`中的Floating Label是在全局主题色的基础上另外定义的，所以`$setTheme`方法暂时无法覆盖到。
> 
> 当前推荐使用Sass变量复写即可达成你要的全局主题效果：
> 
> ```css-scss
> // `/path/to/_vendors.scss`
> @use '@material/theme/variables' as theme-variables with (
>   $primary: #2196F3,
>   $secondary: #2196F3
> );
> 
> @use 'balm-ui/dist/balm-ui.scss';
> ```

感谢回复，经测试，该标签颜色已被覆盖。
![Snipaste_2020-05-19_09-20-05](https://user-images.githubusercontent.com/26089739/82274141-f95b6900-99b1-11ea-829a-f5ff81af66ce.png)
