### ISSUE TITLE
Manual custom grid for global

### ISSUE THREAD

**Issue by ulrichkouame** [balmjs/balm-ui#92]
**Development Relevant Information:**

Please, what is the right way to integrate Manual custom grid for global?
const $ setGrid = useGrid () gives me an empty value

**Comment by elf-mouse** [comment]
Hi @ulrichkouame ,

Please use `$grid.set` instead. The grid docs has been updated.

```js
const $grid = useGrid();
// $grid.set
```

Thank you very very much :)
