### ISSUE TITLE
ui-dialog does not reappear when closed with scrim

### ISSUE THREAD

**Issue by siloam** [balmjs/balm-ui#93]
**Development Relevant Information:**

- BalmUI version: 3.98.2
- Browser: Chrome 96.0.4664.45
- Operating System: Win 10

### Description:
DIalog window does not reappear when closed with scrim
(;maskClosable="true")
### Steps To Reproduce:
Just try it.

**Comment by elf-mouse** [comment]
Sorry, I didn't reproduce the problem.

Can you provide an online demo?
