### ISSUE TITLE
Data table header columns not correct width / alignment

### ISSUE THREAD

**Issue by HDShabe** [balmjs/balm-ui#99]
Hi,

I've just noticed, I'm not sure if it's been since I just updated to fix another bug that you had a fix for, but none of the headers on a datatable seem to have the right width as their row column widths?

Even on the example page: https://next-material.balmjs.com/#/data-display/table

You can see they're not aligned (i.e. the headers are all to the left):

![image](https://user-images.githubusercontent.com/42472545/145837318-c95101c6-31d4-4fb9-9dd3-53b5893645ae.png)

Is this intentional?

Cheers.

**Comment by HDShabe** [comment]
Just to add to this, it only seems to happen when the resolution is relatively wide, it starts at around 1920 width onwards on the example datatable from the example above.

**Comment by elf-mouse** [comment]
Hi @HDShabe ,

This problem has been optimized in the new version.

Thanks again.
